postsubmits:
  - name: post-banka-2-backend-users-prod-postsubmits
    labels:
      preset-harbor-robot-push: "true"
    decorate: true
    always_run: true
    branches:
      - ^main$
    spec:
      serviceAccountName: prow-admin
      containers:
        - image: harbor.k8s.elab.rs/base-images/base:java-17-node-18-docker
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail
              
              #####################################
              # Define environment/namespace vars #
              #####################################
              
              export env=prod
              export side=backend
              export namespace=banka-2-$env
              
              ##############
              # Call setup #
              ##############

              bash kubernetes/upgrade.sh
              chmod +x upgrade.sh
              bash upgrade.sh

          securityContext:
            privileged: true
          imagePullPolicy: Always