version: "3.4"

services:

  dbusers:
    image: mariadb:10.6
    container_name: dbusers
    restart: on-failure
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "bash", "/healthcheck.sh" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 15s
    volumes:
      - ./docker/healthcheck/dbusers/healthcheck.sh:/healthcheck.sh:ro
      - ./docker/provision/dbusers/dbusers-init.sql:/docker-entrypoint-initdb.d/dbusers-init.sql:ro
      - dbusers:/var/lib/mysql
    networks:
      - net_all

  dbexchange:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: dbexchange
    restart: on-failure
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "bash", "/healthcheck.sh" ]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 15s
    volumes:
      - ./docker/healthcheck/dbexchange/healthcheck.sh:/healthcheck.sh:ro
      - ./docker/provision/dbexchange/dbexchange-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - dbexchange:/var/lib/mongodb
    networks:
      - net_all

  flyway:
    image: flyway/flyway:9
    container_name: flyway
    restart: on-failure
    command: "-url=jdbc:mariadb://dbusers:3306/users-dev -schemas=users -user=root -password=root -connectRetries=60 migrate &&
              -url=jdbc:mariadb://dbusers:3306/users-test -schemas=users -user=root -password=root -connectRetries=60 migrate &&
              -url=jdbc:mariadb://dbusers:3306/users-prod -schemas=users -user=root -password=root -connectRetries=60 migrate"
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
      - ./flywayConfig:/flyway/conf
    depends_on:
      dbusers:
        condition: service_healthy
    networks:
      - net_all

  banka2backend-dev:
    container_name: banka2backend-dev
    image: banka2backend-dev
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      dbusers:
        condition: service_healthy
      dbexchange:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    networks:
      - net_all

  banka2backend-prod:
    container_name: banka2backend-prod
    image: banka2backend-prod
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      dbusers:
        condition: service_healthy
      dbexchange:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    networks:
      - net_all

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "8081"
    ports:
      - "8081:80"
    environment:
      PMA_HOST: dbusers
      PMA_PORT: 3306
      MYSQL_ROOT_USER: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      dbusers:
        condition: service_healthy
    networks:
      - net_all


volumes:
  dbusers:
  dbexchange:

networks:
  net_all:
    driver: bridge