version: "3"

services:

  db-users:
    image: mariadb:10.6
    restart: on-failure
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: users
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - db-users:/var/lib/mysql
    networks:
      db:

  flyway:
    image: flyway/flyway:9
    restart: on-failure
    command: -url=jdbc:mariadb://db-users:3306/users -schemas=users -user=root -password=root -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db-users
    networks:
      - db

  banka2backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      spring.datasource.jdbcUrl: jdbc:mariadb://db-users:3306/users
    ports:
      - "8080:8080"
    depends_on:
      - db-users
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "8081"
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db-users
      PMA_PORT: 3306
      MYSQL_ROOT_USER: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - db-users
    networks:
      - db


volumes:
  db-users:
  #mongodb:

networks:
  db:
    driver: bridge