version: "3"

services:

  dbusers:
    image: mariadb:10.6
    container_name: dbusers
    restart: on-failure
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: users
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - dbusers:/var/lib/mysql
    networks:
      db:

  dbexchange:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: dbexchange
    restart: on-failure
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - dbexchange:/var/lib/mongodb
    networks:
      - db

  flyway:
    image: flyway/flyway:9
    command: -url=jdbc:mariadb://dbusers:3306/users -schemas=users -user=root -password=root -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
      - ./flywayConfig:/flyway/conf
    depends_on:
      - dbusers
    networks:
      - db

  banka2backend-dev:
    container_name: banka2backend-dev
    image: banka2backend-dev
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - dbusers
    networks:
      - db

  banka2backend-prod:
    container_name: banka2backend-prod
    image: banka2backend-prod
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - dbusers
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "8081"
    ports:
      - "8081:80"
    environment:
      PMA_HOST: dbusers
      PMA_PORT: 3306
      MYSQL_ROOT_USER: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - dbusers
    networks:
      - db


volumes:
  dbusers:
  dbexchange:

networks:
  db:
    driver: bridge